# Generated by Django 2.2.27 on 2022-03-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220320_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ('-id',), 'verbose_name': 'Количество ингредиента'},
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique recipe ingredients'),
        ),
    ]
