# Generated by Django 2.2.27 on 2022-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220328_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='api.IngredientAmount', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
