# Generated by Django 2.2.27 on 2022-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220329_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='tags',
            field=models.ManyToManyField(to='api.Tag', verbose_name='Тег'),
        ),
    ]
