# Generated by Django 2.2.27 on 2022-03-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ingredientamount_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='tags',
        ),
    ]
