# Generated by Django 2.2.27 on 2022-03-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220331_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='IngredientAmount', through='api.IngredientAmount', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
