# Generated by Django 2.2.27 on 2022-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220331_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='IngredientAmount', through='api.IngredientAmount', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
